# Requires: PowerShell 7+, git CLI

# Update local repository
git pull

# Get all .ps1 files tracked by git in the repo
$ps1Files = git ls-files "*.ps1" | ForEach-Object { Get-Item $_ }

# Prepare documentation lines
$docLines = @()
foreach ($file in $ps1Files) {
    # Read the file content
    $lines = Get-Content $file.FullName

    # Collect contiguous comment lines from the top of the file
    $docBlock = @()
    foreach ($line in $lines) {
        if ($line -match '^\s*#') {
            $docBlock += ($line -replace '^\s*#\s?', '') # Remove leading # and whitespace
        } elseif ($line -match '^\s*$') {
            continue # skip blank lines at the top
        } else {
            break # stop at first non-comment, non-blank line
        }
    }

    if ($docBlock.Count -gt 0) {
        $doc = $docBlock -join ' '
    } else {
        $doc = "No documentation found."
    }
    $docLines += "* **$($file.Name)**: $doc"
}

# Always overwrite README.md with new documentation
$readmePath = "README.md"
$header = "# PowerShell Scripts Documentation`n"
$intro = "This file is automatically generated. Each script and its documentation are listed below:`n"
$content = $header + $intro + ($docLines -join "`n") + "`n"

Set-Content $readmePath $content

# Commit and push changes
git add $readmePath
git commit -m "Regenerate README with PS1 file documentation"
git push