# Requires: PowerShell 7+, git CLI

# Update local repository
git pull

# Get all .ps1 files tracked by git in the repo
$ps1Files = git ls-files "*.ps1" | ForEach-Object { Get-Item $_ }

# Prepare documentation lines
$docLines = @()
foreach ($file in $ps1Files) {
    # Read the file content
    $lines = Get-Content $file.FullName

    # Try to extract the first documentation block (<# ... #>)
    $docBlock = @()
    $inDocBlock = $false
    foreach ($line in $lines) {
        if ($line -match '^\s*<#$') {
            $inDocBlock = $true
            continue
        }
        if ($inDocBlock) {
            if ($line -match '^\s*#>$') {
                break
            }
            $docBlock += $line.Trim()
        }
    }

    if ($docBlock.Count -gt 0) {
        $doc = $docBlock -join ' '
    } else {
        $doc = "No Info"
    }
    $docLines += "* **$($file.Name)**: $doc"
}

# Always overwrite README.md with new documentation
$readmePath = "README.md"
$header = "# PowerShell Scripts Documentation`n"
$intro = "This file is automatically generated. Each script and its documentation block are listed below:`n"
$content = $header + $intro + ($docLines -join "`n") + "`n"

Set-Content $readmePath $content

# Commit and push changes
git add $readmePath
git commit -m "Regenerate README with PS1 file documentation blocks"
git push